/*
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MathinterpreterRuntimeModule extends AbstractMathinterpreterRuntimeModule {
}
