/*
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathinterpreterScopeProvider extends DelegatingScopeProvider {
}
