/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.assingment2.mathinterpreter.Function;
import org.xtext.assingment2.mathinterpreter.MathinterpreterPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FunctionImpl extends MathExpressionImpl implements Function
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathinterpreterPackage.Literals.FUNCTION;
  }

} //FunctionImpl
