/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.assingment2.mathinterpreter.MDExpression;
import org.xtext.assingment2.mathinterpreter.MathinterpreterPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>MD Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MDExpressionImpl extends PMExpressionImpl implements MDExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MDExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathinterpreterPackage.Literals.MD_EXPRESSION;
  }

} //MDExpressionImpl
