/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.assingment2.mathinterpreter.MathinterpreterPackage;
import org.xtext.assingment2.mathinterpreter.MultiplyDivide;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Multiply Divide</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MultiplyDivideImpl extends MinimalEObjectImpl.Container implements MultiplyDivide
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultiplyDivideImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathinterpreterPackage.Literals.MULTIPLY_DIVIDE;
  }

} //MultiplyDivideImpl
