/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.assingment2.mathinterpreter.MathinterpreterPackage;
import org.xtext.assingment2.mathinterpreter.Negative;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Negative</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NegativeImpl extends NumberImpl implements Negative
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NegativeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathinterpreterPackage.Literals.NEGATIVE;
  }

} //NegativeImpl
