/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.assingment2.mathinterpreter.MathinterpreterPackage;
import org.xtext.assingment2.mathinterpreter.PlusMinus;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Plus Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PlusMinusImpl extends MinimalEObjectImpl.Container implements PlusMinus
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PlusMinusImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathinterpreterPackage.Literals.PLUS_MINUS;
  }

} //PlusMinusImpl
