/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.assingment2.mathinterpreter.MathinterpreterPackage;
import org.xtext.assingment2.mathinterpreter.PowExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pow Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PowExpressionImpl extends MDExpressionImpl implements PowExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PowExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathinterpreterPackage.Literals.POW_EXPRESSION;
  }

} //PowExpressionImpl
