/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Define Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assingment2.mathinterpreter.DefineExpr#getVariables <em>Variables</em>}</li>
 * </ul>
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getDefineExpr()
 * @model
 * @generated
 */
public interface DefineExpr extends MathExpression, DefParenthesis
{
  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.assingment2.mathinterpreter.Variable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getDefineExpr_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVariables();

} // DefineExpr
