/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Parenthesis</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getDefParenthesis()
 * @model
 * @generated
 */
public interface DefParenthesis extends Primary
{
} // DefParenthesis
