/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Divide</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getDivide()
 * @model
 * @generated
 */
public interface Divide extends MultiplyDivide
{
} // Divide
