/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assingment2.mathinterpreter.Model#getMathexpression <em>Mathexpression</em>}</li>
 * </ul>
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Mathexpression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.assingment2.mathinterpreter.MathExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mathexpression</em>' containment reference list.
   * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getModel_Mathexpression()
   * @model containment="true"
   * @generated
   */
  EList<MathExpression> getMathexpression();

} // Model
