/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiply Divide</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getMultiplyDivide()
 * @model
 * @generated
 */
public interface MultiplyDivide extends EObject
{
} // MultiplyDivide
