/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negative</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getNegative()
 * @model
 * @generated
 */
public interface Negative extends org.xtext.assingment2.mathinterpreter.Number
{
} // Negative
