/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PM Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assingment2.mathinterpreter.PMExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.assingment2.mathinterpreter.PMExpression#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.assingment2.mathinterpreter.PMExpression#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getPMExpression()
 * @model
 * @generated
 */
public interface PMExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(PMExpression)
   * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getPMExpression_Left()
   * @model containment="true"
   * @generated
   */
  PMExpression getLeft();

  /**
   * Sets the value of the '{@link org.xtext.assingment2.mathinterpreter.PMExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(PMExpression value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference.
   * @see #setOperator(EObject)
   * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getPMExpression_Operator()
   * @model containment="true"
   * @generated
   */
  EObject getOperator();

  /**
   * Sets the value of the '{@link org.xtext.assingment2.mathinterpreter.PMExpression#getOperator <em>Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' containment reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(EObject value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(MDExpression)
   * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getPMExpression_Right()
   * @model containment="true"
   * @generated
   */
  MDExpression getRight();

  /**
   * Sets the value of the '{@link org.xtext.assingment2.mathinterpreter.PMExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(MDExpression value);

} // PMExpression
