/**
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.mathinterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PM Parenthesis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assingment2.mathinterpreter.PMParenthesis#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getPMParenthesis()
 * @model
 * @generated
 */
public interface PMParenthesis extends Primary
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(PMExpression)
   * @see org.xtext.assingment2.mathinterpreter.MathinterpreterPackage#getPMParenthesis_Expression()
   * @model containment="true"
   * @generated
   */
  PMExpression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.assingment2.mathinterpreter.PMParenthesis#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(PMExpression value);

} // PMParenthesis
