/*
 * generated by Xtext 2.21.0
 */
package org.xtext.assingment2.ide


/**
 * Use this class to register ide components.
 */
class MathinterpreterIdeModule extends AbstractMathinterpreterIdeModule {
}
